version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - misspell
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    gocritic:
      enabled-tags:
        - diagnostic
        - style
